administrator/urls.py
from django.urls import path
from administrator import views

app_name = 'administrator'
urlpatterns = [
    path('', views.admin_dashboard, name='adminDashboard'),
    path('delete-form/<pk>/', views.DeleteContactForm.as_view(), name='deleteContactForm'),
    path('delete-buy-order/<pk>/', views.DeleteBuyOrders.as_view(), name='delete_buy_order'),
    path('delete-sell-order/<pk>/', views.DeleteSellOrders.as_view(), name='delete_sell_order'),

    path('bitcoin-exchange-rates/', views.BitCoinExchange.as_view(), name='bitcoinExchangeRates'),
    path('ripple-exchange-rates/', views.RippleExchangeRates.as_view(), name='ripple_exchange_rates'),
    path('ethereum-exchange-rates/', views.EthereumExchangeRates.as_view(), name='ethereum_exchange_rates'),
    path('pm-exchange-rates/', views.PerfectMoneyExchangeRates.as_view(), name='perfect_money_exchange_rates'),

    path('update-bitcoin-price/<pk>/', views.UpdateBitCoinPrice.as_view(), name='update_bit_coin_price'),
    path('update-ripple-price/<pk>/', views.UpdateRippleBuyPrice.as_view(), name='update_ripple_price'),
    path('update-ethereum-price/<pk>/', views.UpdateEthereumBuyPrice.as_view(), name='update_ethereum_price'),
    path('update-pm-price/<pk>/', views.UpdatePerfectMoneyBuyPrice.as_view(), name='update_perfect_money_price'),

    path('bitcoin-buy-requests/', views.BitCoinBuyRequests.as_view(), name='bitcoin_buy_requests'),
    path('ripple-buy-requests/', views.RippleBuyRequests.as_view(), name='ripple_buy_requests'),
    path('ethereum-buy-requests/', views.EthereumBuyRequests.as_view(), name='ethereum_buy_requests'),
    path('perfect-money-buy-requests/', views.PerfectMoneyBuyRequests.as_view(), name='perfect_money_buy_requests'),

    path('bitcoin-sell-requests/', views.BitCoinSellRequests.as_view(), name='bitCoin_sell_request'),
    path('ripple-sell-requests/', views.RippleSellRequests.as_view(), name='ripple_sell_request'),
    path('ethereum-sell-requests/', views.EthereumSellRequests.as_view(), name='ethereum_sell_request'),
    path('pm-sell-requests/', views.PerfectMoneySellRequests.as_view(), name='pm_sell_request'),

    path('update-bitcoin-sell-price/<pk>/', views.UpdateBitCoinSellPrice.as_view(), name='update_bit_coin_sell_price'),
    path('update-ripple-sell-price/<pk>/', views.UpdateRippleSellPrice.as_view(), name='update_ripple_sell_price'),
    path('update-ethereum-sell-price/<pk>/', views.UpdateEthereumSellPrice.as_view(), name='update_ethereum_sell_price'),
    path('update-pm-sell-price/<pk>/', views.UpdatePerfectMoneySellPrice.as_view(), name='update_pm_sell_price'),

    path('users/', views.RegisteredUsers.as_view(), name='registered_users'),
    path('verify-user/<pk>/', views.VerifyRegisteredUser.as_view(), name='verify_registered_user'),
    path('user-profile/<pk>/', views.RegisteredUserProfile.as_view(), name='registered_user_profile'),

    # for the deleting of wrongly created prices
    # path('list-of-eth-prices/', views.ListOfEthereumSellPrices.as_view(), name='list_of_eth_prices'),
    # path('delete-eth/<pk>/', views.DeleteEthereum.as_view(), name='delete_eth'),

]

crypto/urls.py
from django.urls import path
from crypto import views

app_name = 'crypto'
urlpatterns = [
    path('', views.index, name='landingPage'),
    path('blog/', views.blog, name='blog'),
    path('unverified/', views.Unverified.as_view(), name='verification_process'),
    path('form-success/', views.form_success, name='form_success'),

    path('make_payment/', views.make_payment, name='make_payment'),
    path('confirmed-payment/', views.confirmed_payment, name='confirmed_payment'),
]

frontlineExchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from login.views import administrator, registered_user, views


urlpatterns = [
    path('admin/', admin.site.urls),

    path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),

    path('redirect/', views.redirect_base_on_role, name='redirect_base_on_role'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.CreateWhichUser.as_view(), name='select_user_to_create'),
    path('accounts/signup/admin/', administrator.AdministratorSignUpView.as_view(), name='create_admin'),
    path('accounts/signup/user/', registered_user.RegisteredUserSignUpView.as_view(), name='create_registered_user'),

    path('', include('crypto.urls')),
    path('registered-user/', include('registered_user.urls')),
    # path('', include('website.urls')),
    path('administrator/', include('administrator.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registered_user/urls.py
from django.urls import path
from registered_user import views

app_name = 'registered_user'
urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('sell/', views.Sell.as_view(), name='sell'),
    path('orders/', views.orders, name='orders'),
    # path('', views.dashboard, name='dashboard'),

    path('bitcoin-buy-price/', views.BitCoinBuyView.as_view(), name='bitcoin_buy_price'),

    path('profile/[{`<pk>^#}]/', views.UserProfile.as_view(), name='user_profile'),
    # path('bitcoin-profile/<pk>/', views.BitcoinUserProfile.as_view(), name='bitcoin_user_profile'),

    path('bitcoin/[{`<bitcoin_id>^#}]/', views.bitcoin_view, name='bitcoin'),
    path('ripple/[{`<ripple_id>^#}]/', views.ripple_view, name='ripple'),
    path('ethereum/[{`<ethereum_id>^#}]/', views.ethereum_view, name='ethereum'),
    path('perfect-money/[{`<perfect_money_id>^#}]/', views.perfect_money_view, name='perfect_money'),

    path('sell-bitcoin/[{`<bitcoin_id>^#}]/', views.sell_bitcoin_view, name='sell_bitcoin'),
    path('sell-ripple/[{`<ripple_id>^#}]/', views.sell_ripple_view, name='sell_ripple'),
    path('sell-ethereum/[{`<ethereum_id>^#}]/', views.sell_ethereum_view, name='sell_ethereum'),
    path('sell-pm/[{`<perfect_money_id>^#}]/', views.sell_perfect_money_view, name='sell_perfect_money'),

]

src/paystack/paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

administrator/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from login.models import User
from crypto.models import Contact
from administrator.models import BitCoinBuyPrice, RippleBuyPrice, EthereumBuyPrice, PerfectMoneyBuyPrice
from administrator.models import BitCoinSellPrice, RippleSellPrice, EthereumSellPrice, PerfectMoneySellPrice
from registered_user.models import BitCoin, Ripple, Ethereum, PerfectMoney, BuyOrders, SellOrders
from registered_user.models import SellBitCoin, SellRipple, SellEthereum, SellPerfectMoney
from login.decorators import administrator_required


@login_required
@administrator_required
def admin_dashboard(request):
    buy_orders = BuyOrders.objects.all()
    sell_orders = SellOrders.objects.all()
    contact_form = Contact.objects.all()

    context = {'buy_orders': buy_orders, 'sell_orders': sell_orders, 'contact_form': contact_form}
    template = 'administrator/adminDashboard.html'
    return render(request, template, context)


# for bitcoin rates
@method_decorator([login_required(), administrator_required()], name='dispatch')
class BitCoinExchange(ListView):
    model = BitCoinBuyPrice
    template_name = 'administrator/bitCoinExchange.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdateBitCoinPrice(UpdateView):
    model = BitCoinBuyPrice
    fields = ['new_price']
    template_name = 'administrator/updateBitCoinPrice.html'

    def get_context_data(self, **kwargs):
        kwargs['buy_or_sell'] = "BUY"
        return super().get_context_data(**kwargs)
# end of bitcoin rates


# for ripple rates
@method_decorator([login_required(), administrator_required()], name='dispatch')
class RippleExchangeRates(ListView):
    model = RippleBuyPrice
    template_name = 'administrator/rippleExchangeRates.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdateRippleBuyPrice(UpdateView):
    model = RippleBuyPrice
    fields = '__all__'
    template_name = 'administrator/updateRippleBuyPrice.html'

    def get_context_data(self, **kwargs):
        kwargs['buy_or_sell'] = "BUY"
        return super().get_context_data(**kwargs)
# end of ripple rates


# for ethereum rates
@method_decorator([login_required(), administrator_required()], name='dispatch')
class EthereumExchangeRates(ListView):
    model = EthereumBuyPrice
    template_name = 'administrator/ethereumExchangeRates.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdateEthereumBuyPrice(UpdateView):
    model = EthereumBuyPrice
    fields = '__all__'
    template_name = 'administrator/updateEthereumBuyPrice.html'
# end of ethereum rates


# for perfect money rates
@method_decorator([login_required(), administrator_required()], name='dispatch')
class PerfectMoneyExchangeRates(ListView):
    model = PerfectMoneyBuyPrice
    template_name = 'administrator/perfectMoneyExchangeRates.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdatePerfectMoneyBuyPrice(UpdateView):
    model = PerfectMoneyBuyPrice
    fields = '__all__'
    template_name = 'administrator/updatePMBuyPrice.html'
# end of perfect money rates


@method_decorator([login_required(), administrator_required()], name='dispatch')
class BitCoinBuyRequests(ListView):
    model = BitCoin
    context_object_name = 'bit_coin_request'
    template_name = 'administrator/bitCoinBuyRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class RippleBuyRequests(ListView):
    model = Ripple
    context_object_name = 'ripple_request'
    template_name = 'administrator/rippleBuyRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class EthereumBuyRequests(ListView):
    model = Ethereum
    context_object_name = 'ethereum_request'
    template_name = 'administrator/ethereumBuyRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class PerfectMoneyBuyRequests(ListView):
    model = PerfectMoney
    context_object_name = 'perfect_money_request'
    template_name = 'administrator/perfectMoneyBuyRequests.html'


# for the sell requests
@method_decorator([login_required(), administrator_required()], name='dispatch')
class BitCoinSellRequests(ListView):
    model = SellBitCoin
    template_name = 'administrator/bitCoinSellRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class RippleSellRequests(ListView):
    model = SellRipple
    template_name = 'administrator/rippleSellRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class EthereumSellRequests(ListView):
    model = SellEthereum
    template_name = 'administrator/ethereumSellRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class PerfectMoneySellRequests(ListView):
    model = SellPerfectMoney
    template_name = 'administrator/pmSellRequests.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdateBitCoinSellPrice(UpdateView):
    model = BitCoinSellPrice
    fields = ['new_price']
    template_name = 'administrator/updateBitCoinPrice.html'

    def get_context_data(self, **kwargs):
        kwargs['buy_or_sell'] = "SELL"
        return super().get_context_data(**kwargs)


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdateRippleSellPrice(UpdateView):
    model = RippleSellPrice
    fields = ['new_price']
    template_name = 'administrator/updateRippleBuyPrice.html'

    def get_context_data(self, **kwargs):
        kwargs['buy_or_sell'] = "SELL"
        return super().get_context_data(**kwargs)


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdateEthereumSellPrice(UpdateView):
    model = EthereumSellPrice
    fields = ['new_price']
    template_name = 'administrator/updateEthereumBuyPrice.html'

    def get_context_data(self, **kwargs):
        kwargs['buy_or_sell'] = "SELL"
        return super().get_context_data(**kwargs)


@method_decorator([login_required(), administrator_required()], name='dispatch')
class UpdatePerfectMoneySellPrice(UpdateView):
    model = PerfectMoneySellPrice
    fields = ['new_price']
    template_name = 'administrator/updatePMBuyPrice.html'

    def get_context_data(self, **kwargs):
        kwargs['buy_or_sell'] = "SELL"
        return super().get_context_data(**kwargs)


@method_decorator([login_required(), administrator_required()], name='dispatch')
class RegisteredUsers(ListView):
    model = User
    template_name = 'administrator/listOfUsers.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class VerifyRegisteredUser(UpdateView):
    model = User
    fields = ['is_verified']
    template_name = 'administrator/verify.html'
    success_url = reverse_lazy('administrator:registered_users')


@method_decorator([login_required(), administrator_required()], name='dispatch')
class RegisteredUserProfile(DetailView):
    model = User
    template_name = 'administrator/profileOfUser.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class ListOfContactForms(ListView):
    model = Contact
    template_name = 'administrator/adminDashboard.html'


@method_decorator([login_required(), administrator_required()], name='dispatch')
class DeleteContactForm(DeleteView):
    model = Contact
    success_url = reverse_lazy('administrator:adminDashboard')


@method_decorator([login_required(), administrator_required()], name='dispatch')
class DeleteBuyOrders(DeleteView):
    model = BuyOrders
    success_url = reverse_lazy('administrator:adminDashboard')


class DeleteSellOrders(DeleteView):
    model = SellOrders
    success_url = reverse_lazy('administrator:adminDashboard')

# for the deleting of wrongly created prices
# class ListOfEthereumSellPrices(ListView):
#     model = EthereumSellPrice
#     template_name = 'administrator/ethSellPrice.html'


# class DeleteEthereum(DeleteView):
#     model = EthereumSellPrice
#     success_url = reverse_lazy('administrator:adminDashboard')

login/views/administrator.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView

from login.models import User
from login.forms import AdministratorSignUpForm


class AdministratorSignUpView(CreateView):
    model = User
    form_class = AdministratorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Administrator'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        # login(self.request, user)
        return redirect('administrator:complete_admin_signup')

administrator/templates/administrator/adminDashboard.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %} <title>Welcome {{ user }} | Frontline Exchange</title> {% endblock %}
{% block navLinks %}
<li class="nav-active">
    <a href="#">
        <i class="fa fa-home" aria-hidden="true"></i>
        <span>Dashboard</span>
    </a>
</li>
<li class="nav-parent">
    <a>
        <i class="text-info fa fa-bar-chart-o" aria-hidden="true"></i>
        <span>CHANGE CRYPTO PRICES FOR</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="{% url 'administrator:bitcoinExchangeRates' %}">BITCOIN</a>
        </li>
        <li>
            <a href="{% url 'administrator:ripple_exchange_rates' %}">RIPPLE</a>
        </li>
        <li>
            <a href="{% url 'administrator:ethereum_exchange_rates' %}">ETHEREUM</a>
        </li>
        <li>
            <a href="{% url 'administrator:perfect_money_exchange_rates' %}">PERFECT MONEY</a>
        </li>
    </ul>
</li>
<li class="nav-parent">
    <a>
        <i class="text-primary fa fa-arrow-right" aria-hidden="true"></i>
        <span>BUY REQUESTS FOR</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="{% url 'administrator:bitcoin_buy_requests' %}">BITCOIN</a>
        </li>
        <li>
            <a href="{% url 'administrator:ripple_buy_requests' %}">RIPPLE</a>
        </li>
        <li>
            <a href="{% url 'administrator:ethereum_buy_requests' %}">ETHEREUM</a>
        </li>
        <li>
            <a href="{% url 'administrator:perfect_money_buy_requests' %}">PERFECT MONEY</a>
        </li>
    </ul>
</li>
<li class="nav-parent">
    <a>
        <i class="text-info fa fa-arrow-left" aria-hidden="true"></i>
        <span>SELL REQUESTS FOR</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="{% url 'administrator:bitCoin_sell_request' %}">BITCOIN</a>
        </li>
        <li>
            <a href="{% url 'administrator:ripple_sell_request' %}">RIPPLE</a>
        </li>
        <li>
            <a href="{% url 'administrator:ethereum_sell_request' %}">ETHEREUM</a>
        </li>
        <li>
            <a href="{% url 'administrator:pm_sell_request' %}">PERFECT MONEY</a>
        </li>
    </ul>
</li>
<li>
    <a href="{% url 'administrator:registered_users' %}">
        <i class="text-primary fa fa-users" aria-hidden="true"></i>
        <span>USERS</span>
    </a>
</li>
<li>
    <a href="{% url 'administrator:registered_user_profile' user.pk %}">
        <i class="text-warning fa fa-user" aria-hidden="true"></i>
        <span>MY PROFILE</span>
    </a>
</li>
{% endblock %} {% block body %}
<p class="lead text-center">Buy Requests</p>
<div class="table-responsive">
    <table class="table table-hover table-striped" style="font-size: 16px;">
        <thead>
            <tr>
                <th scope="col">User</th>
                <th scope="col">Email</th>
                <th scope="col">Coin</th>
                <th scope="col">Amount Paid</th>
                <th scope="col">Naira Value</th>
                <th scope="col">Paid</th>
            </tr>
        </thead>
        <tbody>
        {% for buy_order in buy_orders %}
            <tr>
                <th scope="row">{{ buy_order.buy_user.username }}</th>
                <th scope="row">{{ buy_order.buy_user.email }}</th>
                <td>{{ buy_order.buy_coin }}</td>
                <td>{{ buy_order.buy_amount_currency }} {{ buy_order.buy_amount }}</td>
                <td>&#8358; {{ buy_order.buy_amount_in_ngn }}</td>
                <td>{{ buy_order.paid }}</td>
                <td>
                    <form method="post" action="{% url 'administrator:delete_buy_order' buy_order.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<br><br>

<p class="lead text-center">Sell Request</p>
<div class="table-responsive">
    <table class="table table-hover table-striped" style="font-size: 16px;">
        <thead>
            <tr>
                <th scope="col">User</th>
                <th scope="col">Email</th>
                <th scope="col">Coin</th>
                <th scope="col">For Sale</th>
                <th scope="col">Naira Value</th>
            </tr>
        </thead>
        <tbody>
        {% for sell_order in sell_orders %}
            <tr>
                <th scope="row">{{ sell_order.sell_user.username }}</th>
                <th scope="row">{{ sell_order.sell_user.email }}</th>
                <td>{{ sell_order.sell_coin }}</td>
                <td>{{ sell_order.sell_amount_currency }} {{ sell_order.sell_amount }}</td>
                <td>&#8358; {{ sell_order.sell_amount_in_ngn }}</td>
                <td>
                    <form method="post" action="{% url 'administrator:delete_sell_order' sell_order.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<br><br>


<p class="lead text-center">Contact Form</p>
<div class="table-responsive">
    <table class="table table-hover table-striped" style="font-size: 16px;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Name</th>
                <th scope="col">Message</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        {% for fields in contact_form %}
            <tr>
                <th scope="row">{{ fields.pk }}</th>
                <td>{{ fields.email }}</td>
                <td>{{ fields.full_name }}</td>
                <td>{{ fields.message }}</td>
                <td>
                    <form method="post" action="{% url 'administrator:deleteContactForm' fields.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

administrator/templates/administrator/listOfUsers.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %} <title>Welcome {{ user }} | List Of Users</title> {% endblock %}
{% block navLinks %}
<li>
    <a href="{% url 'administrator:adminDashboard' %}">
        <i class="fa fa-home" aria-hidden="true"></i>
        <span>Dashboard</span>
    </a>
</li>
<li class="nav-parent">
    <a>
        <i class="text-info fa fa-bar-chart-o" aria-hidden="true"></i>
        <span>CHANGE CRYPTO PRICES FOR</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="{% url 'administrator:bitcoinExchangeRates' %}">BITCOIN</a>
        </li>
        <li>
            <a href="{% url 'administrator:ripple_exchange_rates' %}">RIPPLE</a>
        </li>
        <li>
            <a href="{% url 'administrator:ethereum_exchange_rates' %}">ETHEREUM</a>
        </li>
        <li>
            <a href="{% url 'administrator:perfect_money_exchange_rates' %}">PERFECT MONEY</a>
        </li>
    </ul>
</li>
<li class="nav-parent">
    <a>
        <i class="text-primary fa fa-arrow-right" aria-hidden="true"></i>
        <span>BUY REQUESTS FOR</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="{% url 'administrator:bitcoin_buy_requests' %}">BITCOIN</a>
        </li>
        <li>
            <a href="{% url 'administrator:ripple_buy_requests' %}">RIPPLE</a>
        </li>
        <li>
            <a href="{% url 'administrator:ethereum_buy_requests' %}">ETHEREUM</a>
        </li>
        <li>
            <a href="{% url 'administrator:perfect_money_buy_requests' %}">PERFECT MONEY</a>
        </li>
    </ul>
</li>
<li class="nav-parent">
    <a>
        <i class="text-info fa fa-arrow-left" aria-hidden="true"></i>
        <span>SELL REQUESTS FOR</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="{% url 'administrator:bitCoin_sell_request' %}">BITCOIN</a>
        </li>
        <li>
            <a href="{% url 'administrator:ripple_sell_request' %}">RIPPLE</a>
        </li>
        <li>
            <a href="{% url 'administrator:ethereum_sell_request' %}">ETHEREUM</a>
        </li>
        <li>
            <a href="{% url 'administrator:pm_sell_request' %}">PERFECT MONEY</a>
        </li>
    </ul>
</li>
<li class="nav-active">
    <a href="{% url 'administrator:registered_users' %}">
        <i class="text-primary fa fa-users" aria-hidden="true"></i>
        <span>USERS</span>
    </a>
</li>
<li>
    <a href="{% url 'administrator:registered_user_profile' user.pk %}">
        <i class="text-warning fa fa-user" aria-hidden="true"></i>
        <span>MY PROFILE</span>
    </a>
</li>
{% endblock %} {% block body %}
{% for fields in object_list %}
<div class="col-md-12 col-lg-6 col-xl-6">
    <section class="panel panel-featured-left panel-featured-info">
        <div class="panel-body">
            <div class="widget-summary">
                <div class="widget-summary-col widget-summary-col-icon">
                    <div class="summary-icon bg-primary">
                        <i class="fa fa-user"></i>
                    </div>
                </div>
                <div class="widget-summary-col">
                    <div class="summary">
                        <h3 class="text-center">{{ fields.username }}</h3>
                        <div class="info">
                            <strong class="lead">{{ fields.email }}</strong><br>
                        </div>
                    </div>
                    <div class="summary-footer">
                        <a href="{% url 'administrator:registered_user_profile' fields.pk %}" class="hugoBtn btn-primary pull-right">View Profile</a>
                        <!--<a href="{% url 'registered_user:sell_perfect_money' user.pk %}" class="hugoBtn btn-success pull-right">View</a>-->
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endfor %}


{% endblock %}