crypto/urls.py
from django.urls import path
from crypto import views

app_name = 'crypto'
urlpatterns = [
    path('', views.index, name='landingPage'),
    path('blog/', views.blog, name='blog'),
    path('unverified/', views.Unverified.as_view(), name='verification_process'),
    path('form-success/', views.form_success, name='form_success'),

    path('make_payment/', views.make_payment, name='make_payment'),
    path('confirmed-payment/', views.confirmed_payment, name='confirmed_payment'),
]

frontlineExchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from login.views import administrator, registered_user, views


urlpatterns = [
    path('admin/', admin.site.urls),

    path("paystack", include(('paystack.urls', 'paystack'), namespace='paystack')),

    path('redirect/', views.redirect_base_on_role, name='redirect_base_on_role'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.CreateWhichUser.as_view(), name='select_user_to_create'),
    path('accounts/signup/admin/', administrator.AdministratorSignUpView.as_view(), name='create_admin'),
    path('accounts/signup/user/', registered_user.RegisteredUserSignUpView.as_view(), name='create_registered_user'),

    path('', include('crypto.urls')),
    path('registered-user/', include('registered_user.urls')),
    # path('', include('website.urls')),
    path('administrator/', include('administrator.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registered_user/urls.py
from django.urls import path
from registered_user import views

app_name = 'registered_user'
urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('sell/', views.Sell.as_view(), name='sell'),
    path('orders/', views.orders, name='orders'),
    # path('', views.dashboard, name='dashboard'),

    path('bitcoin-buy-price/', views.BitCoinBuyView.as_view(), name='bitcoin_buy_price'),

    path('profile/[{`<pk>^#}]/', views.UserProfile.as_view(), name='user_profile'),
    # path('bitcoin-profile/<pk>/', views.BitcoinUserProfile.as_view(), name='bitcoin_user_profile'),

    path('bitcoin/[{`<bitcoin_id>^#}]/', views.bitcoin_view, name='bitcoin'),
    path('ripple/[{`<ripple_id>^#}]/', views.ripple_view, name='ripple'),
    path('ethereum/[{`<ethereum_id>^#}]/', views.ethereum_view, name='ethereum'),
    path('perfect-money/[{`<perfect_money_id>^#}]/', views.perfect_money_view, name='perfect_money'),

    path('sell-bitcoin/[{`<bitcoin_id>^#}]/', views.sell_bitcoin_view, name='sell_bitcoin'),
    path('sell-ripple/[{`<ripple_id>^#}]/', views.sell_ripple_view, name='sell_ripple'),
    path('sell-ethereum/[{`<ethereum_id>^#}]/', views.sell_ethereum_view, name='sell_ethereum'),
    path('sell-pm/[{`<perfect_money_id>^#}]/', views.sell_perfect_money_view, name='sell_perfect_money'),

]

src/paystack/paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

registered_user/models.py
from django.db import models
from login.models import User
from django.urls import reverse

from login.validators import validate_file_size

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)


class CompleteUserRegistration(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    gender = models.CharField(max_length=10, choices=GENDER)
    KYC = models.FileField(validators=[validate_file_size])

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    # def __str__(self):
    #     return self.first_name + " " + self.last_name


class BitCoin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "BTC " + str(self.volume)


class Ripple(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "XRP " + str(self.volume)


class Ethereum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "E " + str(self.volume)


class PerfectMoney(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "PM " + str(self.volume)

# end of the buy models
# start of the sell models


class SellBitCoin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "BTC " + str(self.volume)


class SellRipple(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "XRP " + str(self.volume)


class SellEthereum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "E " + str(self.volume)


class SellPerfectMoney(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    NGN = models.FloatField()
    USD = models.FloatField()
    volume = models.FloatField()

    def get_absolute_url(self):
        return reverse('registered_user:dashboard')

    def __str__(self):
        return "PM " + str(self.volume)


class BuyOrders(models.Model):
    buy_user = models.ForeignKey(User, on_delete=models.CASCADE)
    buy_coin = models.CharField(max_length=100)
    buy_amount = models.FloatField(max_length=100)
    buy_amount_currency = models.CharField(max_length=20)
    buy_amount_in_ngn = models.FloatField()
    paid = models.BooleanField(default=False)
    order_id = models.CharField(max_length=20, default="ABCD")
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __str__(self):
        return str(self.buy_user) + " - " + self.buy_amount_currency + " " + str(self.buy_amount) + " for " + self.buy_coin  


class SellOrders(models.Model):
    sell_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    sell_coin = models.CharField(max_length=100)
    sell_amount = models.FloatField(max_length=100)
    sell_amount_currency = models.CharField(max_length=20)
    sell_amount_in_ngn = models.FloatField()
    sell_order_id = models.CharField(max_length=20, default="ABCDef")
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __str__(self):
        return str(self.sell_user) + " - " + self.sell_amount_currency + " " + str(self.sell_amount) + " for " + self.sell_coin

registered_user/forms.py
from django import forms
from registered_user.models import BitCoin, Ripple, Ethereum, PerfectMoney, CompleteUserRegistration
from registered_user.models import SellBitCoin, SellRipple, SellEthereum, SellPerfectMoney


class BitCoinForm(forms.ModelForm):

    class Meta:
        model = BitCoin
        fields = ('NGN', 'USD', 'volume')


class RippleForm(forms.ModelForm):

    class Meta:
        model = Ripple
        fields = ('NGN', 'USD', 'volume')


class EthereumForm(forms.ModelForm):

    class Meta:
        model = Ethereum
        fields = ('NGN', 'USD', 'volume')


class PerfectMoneyForm(forms.ModelForm):

    class Meta:
        model = PerfectMoney
        fields = ('NGN', 'USD', 'volume')

# end of sell forms
# for registration


class CompleteUserRegistrationForm(forms.ModelForm):

    class Meta:
        model = CompleteUserRegistration
        fields = ('first_name', 'last_name', 'email', 'gender', 'KYC')

# start of sell forms


class SellBitCoinForm(forms.ModelForm):

    class Meta:
        model = SellBitCoin
        fields = ('NGN', 'USD', 'volume')


class SellRippleForm(forms.ModelForm):

    class Meta:
        model = SellRipple
        fields = ('NGN', 'USD', 'volume')


class SellEthereumForm(forms.ModelForm):

    class Meta:
        model = SellEthereum
        fields = ('NGN', 'USD', 'volume')


class SellPerfectMoneyForm(forms.ModelForm):

    class Meta:
        model = SellPerfectMoney
        fields = ('NGN', 'USD', 'volume')

login/views/registered_user.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from login.models import User
from login.forms import RegisteredUserSignUpForm


class RegisteredUserSignUpView(CreateView):
    model = User
    form_class = RegisteredUserSignUpForm
    # success_url = reverse_lazy("registered_user:dashboard")
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Registered User'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if self.request.method == "POST":
            form = RegisteredUserSignUpForm(self.request.POST, self.request.FILES)
            if form.is_valid():
                # check_form = form.save(commit=False)
                form.save()
                return redirect('registered_user:dashboard')
            else:
                # request.session['wrong_file_or_size'] = True
                # request.session['wrong_file_or_size'].set_expiry(5)

                args = {}
                return redirect('create_registered_user')

    #     user = form.save()
    #     # login(self.request, user)
    #     return redirect('registered_user:dashboard')


"2216133060"

registered_user/templates/registered_user/BitcoinUserProfile.html
{{ user.username}}<br><br>


{% for fields in user.bitcoin_set.all %}
	Volume :{{ fields.volume }}<br>
	NGN: {{ fields.NGN }}<br>
	USD: {{ fields.USD }}<br><br>
{% endfor %}

registered_user/templates/registered_user/UserProfile.html
{% extends 'administrator/base.html' %}
{% block navLinks %}{% load static %}
{% block title %} <title>{{ user }} - Profile</title> {% endblock %}
<li>
    <a href="{% url 'registered_user:dashboard' %}">
        <i class="text-warning fa fa-usd" aria-hidden="true"></i>
        <span>BUY</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:sell' %}">
        <i class="text-info fa fa-usd" aria-hidden="true"></i>
        <span>SELL</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:orders' %}">
        <i class="text-info fa fa-shopping-cart" aria-hidden="true"></i>
        <span>Orders</span>
    </a>
</li>
<li class="nav-active">
    <a href="{% url 'registered_user:user_profile' user.pk %}">
        <i class="text-warning fa fa-user" aria-hidden="true"></i>
        <span>MY PROFILE</span>
    </a>
</li>
{% endblock %} {% block body %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title text-center">My Profile</div>
            </div>
            <div class="panel-body">
                <p class="lead">Username <span class="pull-right">{{ user.username }}</span></p>
                <p class="lead">Full Name <span class="pull-right">{{ user.first_name }} {{ user.last_name }}</span></p>
                <p class="lead">Address <span class="pull-right">{{ user.address }}</span></p>
                <p class="lead">City <span class="pull-right">{{ user.city }}</span></p>
                <p class="lead">State <span class="pull-right">{{ user.state }}</span></p>
                <p class="lead">Country <span class="pull-right">{{ user.country }}</span></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

registered_user/templates/registered_user/index.html
{% extends 'administrator/base.html' %}
{% block navLinks %}
{% load static %}
{% block title %} <title>Welcome {{ user }} | Buy Crypto Currencies</title> {% endblock %}
<li class="nav-active">
    <a href="{% url 'registered_user:dashboard' %}">
        <i class="text-warning fa fa-usd" aria-hidden="true"></i>
        <span>BUY</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:sell' %}">
        <i class="text-info fa fa-usd" aria-hidden="true"></i>
        <span>SELL</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:orders' %}">
        <i class="text-info fa fa-shopping-cart" aria-hidden="true"></i>
        <span>Orders</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:user_profile' user.pk %}">
        <i class="text-warning fa fa-user" aria-hidden="true"></i>
        <span>MY PROFILE</span>
    </a>
</li>
{% endblock %}
{% block body %}
{% if user.is_verified %}

<div class="row">
    <div class="col-md-6 col-lg-12 col-xl-6">
        <div class="row">

            {% comment %}
            <strong>Name: </strong>{{ key }} <br>
            <strong>Dollar Price: </strong>{{ value.USD.PRICE }} <br>
            <strong>Naira Price: </strong>{{ value.NGN.PRICE }} <br>
            <strong>Symbol2: </strong>{{ value.NGN.FROMSYMBOL }} <br>
            <strong>Symbol: </strong>{{ value.USD.FROMSYMBOL }} <br>
            <strong>Daily High: </strong>{{ value.USD.HIGHDAY }} <br>
            <strong>Daily Low: </strong>{{ value.USD.LOWDAY }} <br>
            {% endcomment %}
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-info">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-primary">
                                    <i class="fa fa-btc"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h3 class="text-center">BITCOIN</h3>
                                    <div class="info">
                                        <strong class="lead">Buy {{ btc_price }}| Sell {{ btc_sell_price }}</strong><br>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="{% url 'registered_user:bitcoin' user.pk %}" class="hugoBtn btn-primary pull-left">Buy BTC Now</a>
                                    <a href="{% url 'registered_user:sell_bitcoin' user.pk %}" class="hugoBtn btn-success pull-right">Sell BTC Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <!--<div class="col-md-12 col-lg-6 col-xl-6">-->
                <!--<section class="panel panel-featured-left panel-featured-info">-->
                    <!--<div class="panel-body">-->
                        <!--<div class="widget-summary">-->
                            <!--<div class="widget-summary-col widget-summary-col-icon">-->
                                <!--<div class="summary-icon bg-primary">-->
                                    <!--XRP-->
                                <!--</div>-->
                            <!--</div>-->
                            <!--<div class="widget-summary-col">-->
                                <!--<div class="summary">-->
                                    <!--<h3 class="text-center">RIPPLE</h3>-->
                                    <!--<div class="info">-->
                                        <!--<strong class="lead">BUY {{ ripple_price }}| SELL {{ xrp_sell_price }}</strong><br>-->
                                    <!--</div>-->
                                <!--</div>-->
                                <!--<div class="summary-footer">-->
                                    <!--<a href="{% url 'registered_user:ripple' user.pk %}" class="hugoBtn btn-primary pull-left">Buy XRP Now</a>-->
                                    <!--<a href="{% url 'registered_user:sell_ripple' user.pk %}" class="hugoBtn btn-success pull-right">Sell XRP Now</a>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                <!--</section>-->
            <!--</div>-->

            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-info">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-primary">
                                    <!--<img src="{% static 'administrator/img/ethereum.png' %}" width="70%">-->
                                    ETH
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h3 class="text-center">ETHEREUM</h3>
                                    <div class="info">
                                        <strong class="lead">BUY {{ ethereum_price }}| SELL {{ eth_sell_price }}</strong><br>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="{% url 'registered_user:ethereum' user.pk %}" class="hugoBtn btn-primary pull-left">Buy ETH Now</a>
                                    <a href="{% url 'registered_user:sell_ethereum' user.pk %}" class="hugoBtn btn-success pull-right">Sell ETH Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-info">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-primary">
                                    PM
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h3 class="text-center">PERFECT MONEY</h3>
                                    <div class="info">
                                        <strong class="lead">BUY {{ perfect_money_price }}| SELL {{ pm_sell_price }}</strong><br>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="{% url 'registered_user:perfect_money' user.pk %}" class="hugoBtn btn-primary pull-left">Buy PM Now</a>
                                    <a href="{% url 'registered_user:sell_perfect_money' user.pk %}" class="hugoBtn btn-success pull-right">Sell PM Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <input id="p" type="hidden" value="{{ btc_price }}">
            <script>
                var price = document.getElementById('p').value;
                var a = price.substr(4);
                var b = parseFloat(a);
            </script>
        </div>
    </div>
</div>
{% else %}
<h1>You are not Verified Yet</h1>
{% endif %}
{% endblock %}

registered_user/templates/registered_user/sell.html
{% extends 'administrator/base.html' %}
{% block navLinks %}
{% load static %}
{% block title %} <title>Welcome {{ user }} | Sell Crypto Currencies</title> {% endblock %}
<li>
    <a href="{% url 'registered_user:dashboard' %}">
        <i class="text-warning fa fa-usd" aria-hidden="true"></i>
        <span>BUY</span>
    </a>
</li>
<li class="nav-active">
    <a href="{% url 'registered_user:sell' %}">
        <i class="text-info fa fa-usd" aria-hidden="true"></i>
        <span>SELL</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:orders' %}">
        <i class="text-info fa fa-shopping-cart" aria-hidden="true"></i>
        <span>Orders</span>
    </a>
</li>
<li>
    <a href="{% url 'registered_user:user_profile' user.pk %}">
        <i class="text-warning fa fa-user" aria-hidden="true"></i>
        <span>MY PROFILE</span>
    </a>
</li>
{% endblock %}
{% block body %}

<div class="row">
    <div class="col-md-6 col-lg-12 col-xl-6">
        <div class="row">

            {% comment %}
            <strong>Name: </strong>{{ key }} <br>
            <strong>Dollar Price: </strong>{{ value.USD.PRICE }} <br>
            <strong>Naira Price: </strong>{{ value.NGN.PRICE }} <br>
            <strong>Symbol2: </strong>{{ value.NGN.FROMSYMBOL }} <br>
            <strong>Symbol: </strong>{{ value.USD.FROMSYMBOL }} <br>
            <strong>Daily High: </strong>{{ value.USD.HIGHDAY }} <br>
            <strong>Daily Low: </strong>{{ value.USD.LOWDAY }} <br>
            {% endcomment %}
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-quartenary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-quartenary">
                                    <i class="fa fa-btc"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h3 class="text-center">BITCOIN</h3>
                                    <div class="info">
                                        <strong class="lead">Buy {{ btc_price }}| Sell {{ btc_sell_price }}</strong><br>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="{% url 'registered_user:bitcoin' user.pk %}" class="hugoBtn btn-primary pull-left">Buy BTC Now</a>
                                    <a href="{% url 'registered_user:sell_bitcoin' user.pk %}" class="hugoBtn btn-success pull-right">Sell BTC Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <!--<div class="col-md-12 col-lg-6 col-xl-6">-->
                <!--<section class="panel panel-featured-left panel-featured-quartenary">-->
                    <!--<div class="panel-body">-->
                        <!--<div class="widget-summary">-->
                            <!--<div class="widget-summary-col widget-summary-col-icon">-->
                                <!--<div class="summary-icon bg-quartenary">-->
                                    <!--XRP-->
                                <!--</div>-->
                            <!--</div>-->
                            <!--<div class="widget-summary-col">-->
                                <!--<div class="summary">-->
                                    <!--<h3 class="text-center">RIPPLE</h3>-->
                                    <!--<div class="info">-->
                                        <!--<strong class="lead">BUY {{ ripple_price }}| SELL {{ xrp_sell_price }}</strong><br>-->
                                    <!--</div>-->
                                <!--</div>-->
                                <!--<div class="summary-footer">-->
                                    <!--<a href="{% url 'registered_user:ripple' user.pk %}" class="hugoBtn btn-primary pull-left">Buy XRP Now</a>-->
                                    <!--<a href="{% url 'registered_user:sell_ripple' user.pk %}" class="hugoBtn btn-success pull-right">Sell XRP Now</a>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                <!--</section>-->
            <!--</div>-->

            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-quartenary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-quartenary">
                                    <!--<img src="{% static 'administrator/img/ethereum.png' %}" width="70%">-->
                                    ETH
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h3 class="text-center">ETHEREUM</h3>
                                    <div class="info">
                                        <strong class="lead">BUY {{ ethereum_price }}| SELL {{ eth_sell_price }}</strong><br>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="{% url 'registered_user:ethereum' user.pk %}" class="hugoBtn btn-primary pull-left">Buy ETH Now</a>
                                    <a href="{% url 'registered_user:sell_ethereum' user.pk %}" class="hugoBtn btn-success pull-right">Sell ETH Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-quartenary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-quartenary">
                                    PM
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h3 class="text-center">PERFECT MONEY</h3>
                                    <div class="info">
                                        <strong class="lead">BUY {{ perfect_money_price }}| SELL {{ pm_sell_price }}</strong><br>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="{% url 'registered_user:perfect_money' user.pk %}" class="hugoBtn btn-primary pull-left">Buy PM Now</a>
                                    <a href="{% url 'registered_user:sell_perfect_money' user.pk %}" class="hugoBtn btn-success pull-right">Sell PM Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <input id="p" type="hidden" value="{{ btc_price }}">
            <script>
                var price = document.getElementById('p').value;
                var a = price.substr(4);
                var b = parseFloat(a);
            </script>
        </div>
    </div>
</div>

{% endblock %}